name: 'ROS 2 Build and Test Project'
description: 'Build and test a ROS 2 project from source'
author: 'ICHIRO ITS'
branding:
  icon: 'activity'
  color: 'gray-dark'
inputs:
runs:
  using: 'composite'
  steps:
