name: 'ROS 2 Build and Test Project'
description: 'Build and test a ROS 2 project from source'
author: 'ICHIRO ITS'
branding:
  icon: 'activity'
  color: 'gray-dark'
inputs:
  ros2-distro:
    description: 'The ROS 2 distribution to be used.'
    required: false
    default: 'foxy'
runs:
  using: 'composite'
  steps:
    - name: Setup dependencies
      run: bash ${{ github.action_path }}/scripts/setup-dependencies.bash ${{ inputs.ros2-distro }}
      shell: bash
    - name: Build and test project
      run: bash ${{ github.action_path }}/scripts/build-and-test.bash ${{ inputs.ros2-distro }}
      shell: bash
